project_id = "thghyespvzejcveiqdhk"

[functions.paint-pixel-dev]
verify_jwt = false

[functions.auth-nonce]
verify_jwt = false

[functions.auth-verify]
verify_jwt = false

[functions.user-update]
verify_jwt = false

[functions.game-validate]
verify_jwt = false

[functions.game-commit]
verify_jwt = false

[functions.rebalance-tick]
verify_jwt = false
